version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - apt-get update -y
      - apt-get install maven -y
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - '**/*'
